table Customers
	lineageTag: 85498845-f11c-4da9-9528-16efed6c9b38

	column Customer_ID
		dataType: string
		lineageTag: 9ed6d7c1-7bae-4730-bba4-52ce6f73a257
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Customer_Name
		dataType: string
		lineageTag: cca64e54-46dc-4e96-8631-3cc21533de6a
		summarizeBy: none
		sourceColumn: Customer_Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 516c0984-5c49-48f0-8554-9dd6e98fc564
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 99669255-3dc4-4048-ad1a-1f32a618c323
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: e5308c96-fde2-4498-8de9-e05cc68da7fb
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Tripti Sahu\Desktop\P\Sales Performance Dashboard\Sales_Performance_Dashboard_Dataset.xlsx"), null, true),
				    Customers_Sheet = Source{[Item="Customers",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Customers_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Column1"}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Duplicates", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer_ID", type text}, {"Customer_Name", type text}, {"Segment", type text}, {"City", type text}, {"State", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

