table Sales
	lineageTag: 38f83277-25ec-447d-ab53-b6da50bcab08

	measure 'Total Sales' =
			
			SUMX(
			    Sales,
			    Sales[Quantity] *
			    Sales[Unit_Price] *
			    (1 - Sales[Discount])
			)
		formatString: "₹"#,0;#,0\ -"₹";"₹"#,0
		lineageTag: 44904b0e-86a2-4970-99e2-8e89ed409ca2

		annotation PBI_FormatHint = {"currencyCulture":"gu-IN"}

	measure 'Total Cost' =
			
			SUMX(
			    Sales,
			    Sales[Quantity] *
			    Sales[Cost_Per_Unit]
			)
		formatString: "₹"#,0.00;#,0.00\ -"₹";"₹"#,0.00
		lineageTag: d64a942f-0be1-4990-8863-ab1badfe92ad

		annotation PBI_FormatHint = {"currencyCulture":"gu-IN"}

	measure 'Total Profit' =
			
			[Total Sales] - [Total Cost]
		formatString: "₹"#,0.00;#,0.00\ -"₹";"₹"#,0.00
		lineageTag: e75240b6-0ed7-49c5-92d0-2997af6d271f

		annotation PBI_FormatHint = {"currencyCulture":"gu-IN"}

	measure 'Profit Margin' =
			
			DIVIDE(
			    [Total Profit],
			    [Total Sales]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: f8e058a8-cc27-44d1-a9f4-f1ed8a09985f

	measure 'Total Units' =
			
			SUM(Sales[Quantity])
		formatString: 0
		lineageTag: 30824eb7-c312-4e42-82d3-02a675e01cf7

	measure 'Total Orders' =
			
			DISTINCTCOUNT(Sales[Order_ID])
		formatString: 0
		lineageTag: 22ad8cb5-8a6c-4473-9c4c-0fa505a221ec

	measure 'Average Order Value' =
			
			DIVIDE(
			    [Total Sales],
			    [Total Orders]
			)
		formatString: "₹"#,0;#,0\ -"₹";"₹"#,0
		lineageTag: ae49e4a5-0ed8-4bdf-832d-3fb2e1644d52

		annotation PBI_FormatHint = {"currencyCulture":"gu-IN"}

	measure 'Previous Year Sales' =
			
			CALCULATE(
			    [Total Sales],
			    SAMEPERIODLASTYEAR('Date'[Date])
			)
		lineageTag: 34c9de03-9d8c-4a01-a78e-3b7e7b252aed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'YoY Growth %' =
			
			DIVIDE(
			    [Total Sales] - [Previous Year Sales],
			    [Previous Year Sales]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 1e1c08af-354d-4247-865e-0166d806d5c1

	measure 'YTD Sales' =
			
			TOTALYTD(
			    [Total Sales],
			    'Date'[Date]
			)
		lineageTag: da51f24c-a447-41a4-a759-648da235a2c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Year Profit' =
			
			CALCULATE(
			    [Total Profit],
			    SAMEPERIODLASTYEAR('Date'[Date])
			)
		lineageTag: d4aa8ff8-ee83-4041-ab01-a58cfa293851

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit Growth %' =
			
			DIVIDE(
			    [Total Profit] - [Previous Year Profit],
			    [Previous Year Profit]
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 43574d04-a727-4bea-9fe3-61db69921b96

	column Order_ID
		dataType: string
		lineageTag: 876118d8-8558-4b29-b2d7-c11ea461c102
		summarizeBy: none
		sourceColumn: Order_ID

		annotation SummarizationSetBy = Automatic

	column Order_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 72d44415-1b73-47a3-a93a-d892305a7079
		summarizeBy: none
		sourceColumn: Order_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Customer_ID
		dataType: string
		lineageTag: f0079f09-5361-47da-a617-880c3b4f3095
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Product_ID
		dataType: string
		lineageTag: c669afa0-0777-4079-a8fc-05c26f4a03e3
		summarizeBy: none
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	column Salesperson_ID
		dataType: string
		lineageTag: 7cb7dd62-2f2e-4b26-8e60-b7aa5cd96ba0
		summarizeBy: none
		sourceColumn: Salesperson_ID

		annotation SummarizationSetBy = Automatic

	column Region_ID
		dataType: string
		lineageTag: b328c3ad-35b7-4066-bb15-ac1d16d07a91
		summarizeBy: none
		sourceColumn: Region_ID

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: e614815e-4d9f-406c-a45f-5461c327d570
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Unit_Price
		dataType: double
		formatString: 0
		lineageTag: 31f90eff-7ec9-4166-8d38-ec3f167e7848
		summarizeBy: sum
		sourceColumn: Unit_Price

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: f9911c9d-2352-4a71-8458-0b6c54701b74
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cost_Per_Unit
		dataType: double
		formatString: 0
		lineageTag: bd0ec0ef-f889-4d82-acc5-e494a3eb65c4
		summarizeBy: sum
		sourceColumn: Cost_Per_Unit

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Tripti Sahu\Desktop\P\Sales Performance Dashboard\Sales_Performance_Dashboard_Dataset.xlsx"), null, true),
				    Sales_Sheet = Source{[Item="Sales",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sales_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order_ID", type text}, {"Order_Date", type date}, {"Customer_ID", type text}, {"Product_ID", type text}, {"Salesperson_ID", type text}, {"Region_ID", type text}, {"Quantity", Int64.Type}, {"Unit_Price", type number}, {"Discount", type number}, {"Cost_Per_Unit", type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",null,0,Replacer.ReplaceValue,{"Discount"}),
				    #"Removed Duplicates" = Table.Distinct(#"Replaced Value"),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each true),
				    #"Replaced Value1" = Table.ReplaceValue(#"Filtered Rows",null,0,Replacer.ReplaceValue,{"Cost_Per_Unit"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value1", each true)
				in
				    #"Filtered Rows1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

